accounts/urls.py
# -*- coding: utf-8 -*-
from django.contrib.auth.views import LogoutView
from django.urls import path
from accounts.views import (
    CustomLoginView,
    SignUpView,
    SignerUserUpdateView,
    activate,
    SignerUserListView,
    SignerDetailsView,
)

app_name = "accounts"
urlpatterns = [
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", SignUpView.as_view(), name="signup"),
    path("<int:pk>/add-signer/", SignerUserUpdateView.as_view(), name="add-signer"),
    path("activate/<uidb64>/<token>/", activate, name="activate"),
    path("signers/", SignerUserListView.as_view(), name="signers"),
    path("<int:pk>/", SignerDetailsView.as_view(), name="detail"),
]

signature_validator/urls.py
# -*- coding: utf-8 -*-
from django.urls import path

from signature_validator.views import (
    ValidateSignatureView,
    PDFResultView,
    ValidatedPDFListView,
    ReportView,
    PDFResultReportView,
    generate_pdf_report,
)


app_name = "signature-validator-view"
urlpatterns = [
    path("", ValidateSignatureView.as_view(), name="validate-signature"),
    path("pdf-result/<int:pk>/", PDFResultView.as_view(), name="pdf-result"),
    path(
        "pdf-result/<int:pk>/pdf-report",
        PDFResultReportView.as_view(),
        name="pdf-result-report",
    ),
    path(
        "pdf-result/<int:pk>/pdf-download",
        generate_pdf_report,
        name="pdf-result-download",
    ),
    path(
        "pdf-validated_list", ValidatedPDFListView.as_view(), name="validated-pdf-list"
    ),
    path("report", ReportView.as_view(), name="report"),
]

validator/urls.py
# -*- coding: utf-8 -*-
"""
URL configuration for validator project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.0/topics/http/urls/

Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))

"""

from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)
from rest_framework.routers import DefaultRouter
import accounts.api.urls
import signature_validator.api.urls
from django.conf.urls.static import static


router = DefaultRouter()

router.registry.extend(accounts.api.urls.router.registry)
router.registry.extend(signature_validator.api.urls.router.registry)


urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/", include(router.urls)),
    path("api/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("api/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("api/token/verify/", TokenVerifyView.as_view(), name="token_verify"),
    path("", include("signature_validator.urls", namespace="signature-validator-view")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    # path('users/', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base/css.html
{% load static %}

<link rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
      integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ"
      crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/footer.css' %}">

templates/base/footer.html
{% load static %}
<footer class="bg-light">
    <div class="row">
        <div class="col-sm-6 col-md-4 footer-navigation">
            <h3>
                <a href="{% url 'signature-validator-view:validate-signature' %}">
                    <img src="{% static 'img/logo-transparent.png' %}" style="max-height: 40px"
                         alt="Logo">
                </a>

            </h3>
            <p class="links">
                <a href="{% url 'signature-validator-view:validate-signature' %}">Home</a>
                <strong>&nbsp; · </strong>

            <p class="company-name">PDF Validator © 2024</p>
            <p class="company-name">Project By:
                <a href="/">DonDevs Developers</a>
            </p>
        </div>
        <div class="col-sm-6 col-md-4 mt-5 footer-contacts">
            <div>
                <p>
                    <i class="fa fa-address-book" aria-hidden="true"></i>
                    <span >331/5A, Palenwatte, </span > Pannipitiya
                </p>
            </div>
            <div>

                <p class="footer-center-info email text-left">
                    <i class="fa fa-phone" aria-hidden="true"></i>
                    <a href="tel:+94-770-783-209">+94-770-078-3209</a>
                </p>
            </div>
            <div><i class="fa fa-envelope" aria-hidden="true"></i>
                <a href="mailto:3rule57@gmail.com " target="_blank">
                    3rule57@gmail.com
                </a>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="col-md-4 footer-about mt-5">
            <h4>About the company</h4>
            <p> We’re a company that focusses on PDF validation </p>
        </div>
    </div>
</footer>

templates/base/js.html
<script
        src="https://code.jquery.com/jquery-3.3.1.js"
        integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>

templates/base/messages.html
<div class="col-12 col-md-6 col-lg-4 ml-auto">
    {% if messages %}
    {% for message in messages %}
      <div class="alert alert-{% if message.tags %}{{ message.tags }} {% endif %} alert-dismissible fade show"
           role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
          </button>
      </div>
    {% endfor %}
    {% endif %}
</div>

templates/base/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'signature-validator-view:validate-signature' %}">
         <img src="{% static 'img/logo-transparent.png' %}" style="max-height: 40px" alt="Logo">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"
            aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'signature-validator-view:validated-pdf-list' %}">My Validated PDF's</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:signers' %}">Check Signers</a>
            </li>
            {% if user.is_authenticated and user.user_type == 'signer'  %}
                {% if user.signer_user and not user.signer_user.public_key %}
                    <li class="nav-item">
                        <a class="nav-link"
                           href="{% url 'accounts:add-signer' user.signer_user.pk %}"> Add Public
                            Key</a>
                    </li>
                {% endif %}
            {% endif %}
            {% if user.is_authenticated and user.is_superuser %}
                <li class="nav-item">
                    <a class="nav-link"
                       href="{% url 'signature-validator-view:report' %}">Analytics</a>
                </li>
            {% endif %}

        </ul>
        <ul class="navbar-nav ml-auto">

            {% if user.is_authenticated %}
                <li class="nav-item">
                    <span class="nav-link" href="">Hi, {{ user.username }} </span>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#"
                       onClick="document.getElementById('logoutform').submit()">
                        Logout
                    </a>
                </li>
                <form id="logoutform" method="POST" action="{% url 'accounts:logout' %}">
                    {% csrf_token %}
                    <input type="hidden">
                </form>
            {% else %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'accounts:login' %}">Sign In </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

templates/base/paginator.html
{% load static %}
<div class="col-12 d-flex justify-content-center">
    {% if is_paginated %}

        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-4"
               href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}
    {% endif %}
</div>