accounts/api/urls.py
# -*- coding: utf-8 -*-
from rest_framework.routers import DefaultRouter

from accounts.api.views import SignerUserViewSet


router = DefaultRouter()
router.register("signers", SignerUserViewSet, "signers")


urlpatterns = router.urls

accounts/urls.py
# -*- coding: utf-8 -*-
from django.contrib.auth.views import LogoutView
from django.urls import path
from accounts.views import (
    CustomLoginView,
    SignUpView,
    SignerUserUpdateView,
    activate,
    SignerUserListView,
    SignerDetailsView,
)

app_name = "accounts"
urlpatterns = [
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", SignUpView.as_view(), name="signup"),
    path("<int:pk>/add-signer/", SignerUserUpdateView.as_view(), name="add-signer"),
    path("activate/<uidb64>/<token>/", activate, name="activate"),
    path("signers/", SignerUserListView.as_view(), name="signers"),
    path("<int:pk>/", SignerDetailsView.as_view(), name="detail"),
]

validator/urls.py
# -*- coding: utf-8 -*-
"""
URL configuration for validator project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.0/topics/http/urls/

Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))

"""

from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)
from rest_framework.routers import DefaultRouter
import accounts.api.urls
import signature_validator.api.urls
from django.conf.urls.static import static


router = DefaultRouter()

router.registry.extend(accounts.api.urls.router.registry)
router.registry.extend(signature_validator.api.urls.router.registry)


urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/", include(router.urls)),
    path("api/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("api/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("api/token/verify/", TokenVerifyView.as_view(), name="token_verify"),
    path("", include("signature_validator.urls", namespace="signature-validator-view")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    # path('users/', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
# -*- coding: utf-8 -*-
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _


class CustomUser(AbstractUser):
    """Custom User Model."""

    class UserType(models.TextChoices):
        signer = ("signer", "Signer")
        validator = ("validator", "Validator")

    user_type = models.CharField(
        max_length=10,
        choices=UserType.choices,
        default=UserType.validator,
    )
    email = models.EmailField(_("email address"), unique=True)
    is_active = models.BooleanField(
        _("active"),
        default=False,
        help_text=_(
            "Designates whether this user should be treated as active. "
            "Unselect this instead of deleting accounts."
        ),
    )

    def __str__(self):
        return f"{self.username}-{self.email}"


class SignerUser(models.Model):
    """Model for Signer User."""

    public_key = models.TextField(
        unique=True, blank=True, null=True, help_text="Public key of the Signer"
    )
    nic_number = models.CharField(
        max_length=15, help_text="National Identity Card Number of the Signer"
    )
    user = models.OneToOneField(
        CustomUser,
        on_delete=models.CASCADE,
        related_name="signer_user",
        blank=True,
        null=True,
    )
    certificate = models.FileField(
        upload_to="certificates/", help_text="Certificate of the Signer"
    )
    nic_image = models.FileField(
        upload_to="nics/", help_text="National Identity Card Image of the Signer"
    )
    profile_image = models.FileField(
        upload_to="profile_images/", help_text="Profile Image of the Signer"
    )
    verification_email_sent = models.BooleanField(
        default=False, help_text="Verification email sent to the signer user"
    )
    active = models.BooleanField(
        default=False, help_text="Signer user is active or not"
    )
    rejected = models.BooleanField(
        default=False, help_text="Signer user is rejected or not"
    )

    def __str__(self):
        """Return the string representation of the object."""
        return f"{self.pk}"


class ValidatorUser(models.Model):
    """Model for Validator User."""

    user = models.OneToOneField(
        CustomUser, on_delete=models.CASCADE, related_name="validator_user"
    )
    organization = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        """Return the string representation of the object."""
        return f"{self.user.username}-{self.user.email}"

accounts/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.contrib.auth.forms import UserCreationForm
import re

from validator.logger import module_logger
from .models import CustomUser, SignerUser
from .services.pbs_extractor_service import PublicKeyExtractor

logger = module_logger(__name__)


class CustomUserCreationForm(UserCreationForm):
    """Custom User Creation Form."""

    user_type = forms.ChoiceField(
        label="User Type",
        choices=CustomUser.UserType.choices,
        initial=CustomUser.UserType.signer,
    )

    class Meta:
        model = CustomUser
        fields = ("username", "email", "user_type", "first_name", "last_name")
        widgets = {
            "password": forms.PasswordInput(),
        }


class SignerUserForm(forms.ModelForm):
    """Signer User ModelForm class."""

    class Meta:
        """Metaclass for SignerUserForm."""

        model = SignerUser
        fields = ("nic_number", "certificate", "nic_image", "profile_image")
        labels = {
            "nic_number": "National Identity Card Number",
            "certificate": "Certificate",
            "nic_image": "National Identity Card Image",
            "profile_image": "Profile Image",
        }

    def __init__(self, *args, **kwargs):
        """Initialize the form with user object."""
        self.user = kwargs.pop("user", None)
        self.calculated_public_key = None
        super().__init__(*args, **kwargs)

    def clean_nic_number(self):
        """Validate the National Identity Card Number."""
        nic_number = self.cleaned_data.get("nic_number")
        if not nic_number:
            raise forms.ValidationError("National Identity Card Number is required.")
        if not re.match(r"^([0-9]{9}[x|X|v|V]|[0-9]{12})$", nic_number):
            raise forms.ValidationError("Invalid National Identity Card Number.")
        if (
            SignerUser.objects.filter(nic_number=nic_number)
            .exclude(user=self.user)
            .exists()
        ):
            raise forms.ValidationError(
                "This National Identity Card Number is already used,"
                " with a different user."
            )
        return nic_number

    def clean_certificate(self):
        """Validate the certificate."""
        certificate = self.cleaned_data.get("certificate")
        if certificate:
            if certificate.name.split(".")[-1] not in ["fdf", "cer", "p7c"]:
                raise forms.ValidationError(
                    "Invalid certificate file type. Only .fdf, .cer, .p7c are allowed."
                )
            try:
                self.calculated_public_key = PublicKeyExtractor(
                    certificate.name, certificate.read()
                ).get_public_key()
            except Exception as e:
                logger.error(f"Error while extracting public key: {e}")
                raise forms.ValidationError("Invalid certificate.")
        else:
            raise forms.ValidationError("Certificate is required.")
        if (
            SignerUser.objects.filter(public_key=self.calculated_public_key)
            .exclude(user=self.user)
            .exists()
        ):
            raise forms.ValidationError(
                "This certificate is already used, with a different user."
            )
        return certificate

    def save(self, commit=True):
        """Override save method to save the calculated public key."""
        instance = super().save()
        if self.calculated_public_key is not None:
            instance.public_key = self.calculated_public_key
        return instance

accounts/api/views.py
# -*- coding: utf-8 -*-
from rest_framework import viewsets
from rest_framework.permissions import AllowAny, IsAdminUser

from accounts.models import SignerUser
from accounts.permissions import IsOwnerOrReadOnly
from accounts.serializers import SignerUserSerializer


class SignerUserViewSet(viewsets.ModelViewSet):
    """Viewset for signer user model."""

    permission_classes = []
    serializer_class = SignerUserSerializer

    def get_permissions(self):
        """Handle the permissions for the viewset."""
        if self.action == "create":
            return [AllowAny()]
        else:
            # only admin users and owner of the object can perform the action
            return [IsOwnerOrReadOnly(), IsAdminUser()]

    def get_queryset(self):
        """Return active signer users."""
        return SignerUser.objects.filter(user__is_active=True)

accounts/views.py
# -*- coding: utf-8 -*-
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.core.mail import EmailMessage, mail_admins, send_mail
from django.shortcuts import redirect
from django.template.loader import render_to_string
from django.urls import reverse_lazy, reverse
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views.generic import UpdateView, DetailView
from django.views.generic.edit import CreateView
from django_filters.views import FilterView

from validator import settings
from .filters import SignerUserFilter
from .forms import CustomUserCreationForm, SignerUserForm
from .models import CustomUser, SignerUser
from .tokens import account_activation_token


class CustomLoginView(LoginView):
    """Override LoginView to specify template name."""

    template_name = "accounts/login.html"


class SignUpView(CreateView):
    """View for user signup."""

    form_class = CustomUserCreationForm
    template_name = "accounts/signup.html"

    def form_valid(self, form):
        """Save the form and send activation email."""
        user = form.save()

        current_site = self.request.build_absolute_uri("/")[:-1]
        mail_subject = "Activation link has been sent to your email."
        message = render_to_string(
            template_name="accounts/account_activation_email.html",
            context={
                "user": user,
                "domain": current_site,
                "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                "token": account_activation_token.make_token(user),
            },
        )
        to_email = form.cleaned_data.get("email")
        email = EmailMessage(mail_subject, message, to=[to_email])
        email.send()
        messages.success(
            self.request,
            "Please confirm your email address to complete the registration",
        )
        return super().form_valid(form)

    def get_success_url(self):
        """Get the success URL for the view."""
        return reverse_lazy("accounts:login")


class SignerUserUpdateView(LoginRequiredMixin, UpdateView):
    """View for adding signer user."""

    form_class = SignerUserForm
    success_url = reverse_lazy("accounts:login")
    template_name = "accounts/signer.html"

    def get_success_url(self):
        """Get the success URL for the view."""
        return reverse_lazy("signature-validator-view:validate-signature")

    def form_valid(self, form):
        """Save the form and send emails to admin and signer."""
        signer_user = form.save(commit=False)
        signer_user.user = self.request.user
        signer_user.save()
        self.request.get_full_path()
        host = self.request.build_absolute_uri("/")[:-1]
        url = reverse(
            viewname="admin:accounts_signeruser_change",
            args=[self.request.user.signer_user.pk],
        )

        if signer_user.public_key:
            # sending emails to admin to verify the signer
            mail_admins(
                subject=f"Check Verification of Signer {self.request.user.username}",
                message=f"A new signer has been joined, please verify and accept. \n"
                f"Username: {self.request.user.username} \n"
                f"Email: {self.request.user.email} \n"
                f"{host + url}",
                fail_silently=False,
            )
            # sending email to the signer about verification process
            send_mail(
                subject="Signer Verification",
                message="Your verification as a signer is under process, we will notify you soon.",
                recipient_list=[self.request.user.email],
                from_email=settings.EMAIL_HOST_USER,
                fail_silently=False,
            )
            messages.warning(
                self.request,
                "Your verification is under process, we will notify you soon.",
            )
        return super().form_valid(form)

    def get_form_kwargs(self):
        """Get the form kwargs for the view to add logged-in user."""
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def get_queryset(self):
        """Get the queryset for the view."""
        return SignerUser.objects.filter(user=self.request.user)


def activate(request, uidb64, token):
    """Activate the user account."""
    try:
        uid = urlsafe_base64_decode(force_bytes(uidb64).decode("utf-8")).decode("utf-8")
        user = CustomUser.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, CustomUser.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(
            request,
            "Thank you for your email confirmation. "
            "Now you can login to your account.",
        )
        if user.user_type == CustomUser.UserType.signer:
            return redirect(
                reverse_lazy("accounts:add-signer", kwargs={"pk": user.signer_user.pk})
            )
        return redirect(reverse_lazy("accounts:login"))
    else:
        messages.error(request, "Activation link is invalid!")
        return redirect(reverse_lazy("accounts:login"))


class SignerUserListView(FilterView):
    """View for listing all the signers with filters."""

    template_name = "accounts/signer_list.html"
    model = SignerUser
    context_object_name = "signers"
    filterset_class = SignerUserFilter
    paginate_by = 10

    def get_queryset(self):
        """Get the queryset for the view."""
        return SignerUser.objects.filter(active=True)


class SignerDetailsView(LoginRequiredMixin, DetailView):
    """View for updating signer details."""

    model = SignerUser
    template_name = "accounts/signer_detail.html"
    context_object_name = "signer"

accounts/templates/accounts/account_activation_email.html
{% autoescape off %}
Dear {{ user.username }},

Welcome to PDF Validator! We're excited to have you on board. To get started,
please activate your account by clicking the link below:

{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}

If you have any questions or encounter any issues during the activation process,
feel free to reach out to our support team at  3rule57@gmail.com.

Thank you for choosing PDF Validator. We look forward to serving you!

Best regards,
Chanuka
PDF Validator Team

{% endautoescape %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Log In{% endblock %}

{% block content %}
<div class="container">
    <div class="row mt-5">
        <div class="col-lg-6 col-md-4 col-sm-12">

        </div>
        <div class="col-lg-6 col-md-8 col-sm-12">
            <div class="card">
                <div class="card-body">
                    <h2 class="text-danger mb-5">Log in to PDF Validator</h2>
                    <form method="post">
                        {% csrf_token %}
                        {{ form | crispy }}
                        <small class="text-muted">
                            Don't have an account
                            <a class="btn btn-sm btn-link" href="{% url 'accounts:signup' %}">Sign Up for PDF Validator</a>
                        </small>
                        <div class="text-right mt-5">
                            <button class="btn btn-outline-danger border-radius-one" type="submit">Log in</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/signer.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block title %}Add Signer{% endblock %}

{% block content %}
<div class="container">
    <div class="row mt-5">
        <div class="col-lg-6 col-md-4 col-sm-12">

        </div>
        <div class="col-lg-6 col-md-4 col-sm-12">
            <div class="card">
                <div class="card-body">
                <h2 class="text-danger mb-5">Create Signer Profile</h2>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form | crispy }}

                        <div class="text-right mt-5">
                            <button class="btn btn-outline-danger border-radius-one" type="submit">
                                Create
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/signer_detail.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block title %}Signer Detail{% endblock %}


{% block content %}
    <div class="container mt-2 mb-2">
        <div class="row">
            <div class="col-md-8 col-12 mr-auto ml-auto">
                 <h2 class="account-heading text-center"> Profile Details </h2>
                <div class="card mt-5">
                    <div class="card-body">
                        <div class="media">
                            <img class="rounded-circle border-light account-img img-thumbnail"
                                 width="300" height="300"
                                 src="{{ signer.profile_image.url }}" alt="profile-pic"/>
                        </div>
                        <div class="media-body mt-5">
                            <h3> Username:
                                <span class="text-secondary">
                                {{ signer.user.username }}
                                </span>
                            </h3>
                            <h4>
                                Email:
                                <span class="text-secondary">
                                {{ signer.user.email }}
                                </span>
                            </h4>
                            <h4>
                                NIC:
                                <span class="text-secondary">
                                {{ signer.nic_number }}
                                </span>
                            </h4>
                            <h4>
                                Public Key of the signer:
                                <span class="text-secondary">
                                {{ signer.public_key }}
                                </span>
                            </h4>
                            <h4>
                                Date Joined:
                                <span class="text-secondary">
                                {{ signer.user.date_joined }}
                                </span>
                            </h4>
                            <div class="text-right mt-5">
                                <a href="{% url 'accounts:signers' %}"
                                   class="btn btn-primary btn-block ">
                                    Back
                                </a>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
{% endblock content %}

accounts/templates/accounts/signer_list.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load static %}
{% block title %}Signers{% endblock %}

{% block content %}
    <div class="container">
        <div class="row mt-3">
            <div class="col-lg-8 col-sm-12">
                <div class="text-center">
                    <img src="{% static 'img/pdf-search.png' %}" height="200px"
                         class=" d-inline center-image"
                         alt="">
                    <h2 class="d-inline text-danger">Search Signers</h2>
                </div>
            </div>
            <div class="col-lg-4 col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <form method="get" action="">
                            <div class="card-body">
                                {{ filter.form| crispy }}
                            </div>
                            <div class="text-right">
                                <input class="btn btn-outline-secondary border-radius-one" type="submit" value="Filter"/>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="row mt-5">


            <div class="col-12 mt-5">
                <table class="table table-bordered">
                    <thead>
                    {% if signers %}
                        <tr class="font-weight-bold text-center">
                        <th scope="col">ID</th>
                        <th scope="col">Nic Number</th>
                        <th scope="col">Email</th>
                        <th scope="col">Profile Picture</th>
                    </tr>
                    {% endif %}

                    </thead>
                    <tbody>
                    {% for signer in signers %}
                        <tr class="text-center">
                            <td>{{ signer.id }}</td>
                            <td>{{ signer.nic_number }}</td>
                            <td>{{ signer.user.email }}</td>
                            <td>
                                <a href="{% url 'accounts:detail' signer.pk %}">
                                    <img src="{{ signer.profile_image.url }}" alt="profile-image" height="100px" width="100px" class="center-image">
                                </a>
                            </td>
                        </tr>
                    {% empty %}
                        <div class="col-12">
                            <div class="text-center">
                                <img src="{% static 'img/pdf-home.png' %}" height="150px"
                                     class=" d-inline "
                                     alt="">
                                <h2 class="d-inline text-danger">
                                    No Signer Found. Please try different filter option
                                </h2>
                            </div>
                        </div>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    {% include 'base/paginator.html' %}

{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<div class="container">
    <div class="row mt-5">
        <div class="col-lg-6 col-md-4 col-sm-12">

        </div>
        <div class="col-lg-6 col-md-8 col-sm-12">
            <div class="card">
                <div class="card-body">
                <h2 class="text-danger mb-5">Create a new account</h2>
                    <form method="post">
                        {% csrf_token %}
                        {{ form | crispy }}
                        <small class="text-muted">Do you already have an accout?
                            <a class="btn btn-sm btn-link" href="{% url 'accounts:login' %}">Login</a>
                        </small>
                        <div class="text-right mt-5">
                            <button class="btn btn-outline-danger border-radius-one" type="submit">Sign Up</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}