accounts/urls.py
# -*- coding: utf-8 -*-
from django.contrib.auth.views import LogoutView
from django.urls import path
from accounts.views import (
    CustomLoginView,
    SignUpView,
    SignerUserUpdateView,
    activate,
    SignerUserListView,
    SignerDetailsView,
)

app_name = "accounts"
urlpatterns = [
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", SignUpView.as_view(), name="signup"),
    path("<int:pk>/add-signer/", SignerUserUpdateView.as_view(), name="add-signer"),
    path("activate/<uidb64>/<token>/", activate, name="activate"),
    path("signers/", SignerUserListView.as_view(), name="signers"),
    path("<int:pk>/", SignerDetailsView.as_view(), name="detail"),
]

signature_validator/api/urls.py
# -*- coding: utf-8 -*-
from rest_framework.routers import DefaultRouter


from signature_validator.api.views import PdfValidateViewSet


router = DefaultRouter()
router.register("signatures", PdfValidateViewSet, "signatures")


urlpatterns = router.urls

signature_validator/urls.py
# -*- coding: utf-8 -*-
from django.urls import path

from signature_validator.views import (
    ValidateSignatureView,
    PDFResultView,
    ValidatedPDFListView,
    ReportView,
    PDFResultReportView,
    generate_pdf_report,
)


app_name = "signature-validator-view"
urlpatterns = [
    path("", ValidateSignatureView.as_view(), name="validate-signature"),
    path("pdf-result/<int:pk>/", PDFResultView.as_view(), name="pdf-result"),
    path(
        "pdf-result/<int:pk>/pdf-report",
        PDFResultReportView.as_view(),
        name="pdf-result-report",
    ),
    path(
        "pdf-result/<int:pk>/pdf-download",
        generate_pdf_report,
        name="pdf-result-download",
    ),
    path(
        "pdf-validated_list", ValidatedPDFListView.as_view(), name="validated-pdf-list"
    ),
    path("report", ReportView.as_view(), name="report"),
]

validator/urls.py
# -*- coding: utf-8 -*-
"""
URL configuration for validator project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.0/topics/http/urls/

Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))

"""

from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)
from rest_framework.routers import DefaultRouter
import accounts.api.urls
import signature_validator.api.urls
from django.conf.urls.static import static


router = DefaultRouter()

router.registry.extend(accounts.api.urls.router.registry)
router.registry.extend(signature_validator.api.urls.router.registry)


urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/", include(router.urls)),
    path("api/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("api/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("api/token/verify/", TokenVerifyView.as_view(), name="token_verify"),
    path("", include("signature_validator.urls", namespace="signature-validator-view")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    # path('users/', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

signature_validator/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.urls import reverse

from accounts.models import CustomUser, SignerUser


class PdfDocumentValidator(models.Model):
    """Model to store PDF validation data for the whole document."""

    pdf_file = models.FileField(upload_to="pdfs/", blank=False, null=False)
    is_signed = models.BooleanField(default=False)
    is_hashes_valid = models.BooleanField(default=False)
    is_signatures_valid = models.BooleanField(default=False)
    user = models.ForeignKey(
        CustomUser, on_delete=models.SET_NULL, blank=True, null=True
    )
    all_signers_verified = models.BooleanField(default=False)
    distinct_people_signed = models.IntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.pdf_file.name

    def get_absolute_url(self):
        """Get absolute URL for the instance."""
        return reverse("signature-validator-view:pdf-result", kwargs={"pk": self.pk})


class SignatureValidator(models.Model):
    """Model to store signature validation data."""

    pdf_document_validator = models.ForeignKey(
        PdfDocumentValidator, on_delete=models.CASCADE
    )
    serial_number = models.CharField(max_length=255)
    hash_valid = models.BooleanField(default=False)
    signature_valid = models.BooleanField(default=False)
    verified_signer = models.BooleanField(default=False)
    message = models.TextField(blank=True, null=True)
    signing_time = models.DateTimeField()
    signature_name = models.CharField(max_length=255)
    signed_by = models.CharField(max_length=255, blank=True, null=True)
    signer_user = models.ForeignKey(
        SignerUser, blank=True, null=True, on_delete=models.SET_NULL
    )
    email_of_signer = models.CharField(max_length=255, blank=True, null=True)
    signature_algorithm = models.CharField(max_length=255, blank=True, null=True)
    digest_algorithm = models.CharField(max_length=255, blank=True, null=True)
    message_digest = models.TextField(blank=True, null=True)
    public_key = models.TextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.signature_name

signature_validator/api/views.py
# -*- coding: utf-8 -*-
from rest_framework import viewsets
from rest_framework.permissions import AllowAny

from signature_validator.models import PdfDocumentValidator
from signature_validator.serializers import PdfValidateSerializer


class PdfValidateViewSet(viewsets.ModelViewSet):
    """Viewset to validate PDF documents."""

    permission_classes = [AllowAny]
    serializer_class = PdfValidateSerializer

    def get_serializer_context(self):
        """Pass the request object to the serializer."""
        context = super().get_serializer_context()
        context.update({"user": self.request.user})
        return context

    def get_queryset(self):
        """Return active signer users."""
        return PdfDocumentValidator.objects.all()

signature_validator/views.py
# -*- coding: utf-8 -*-
from datetime import timedelta

import pdfkit
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.urls import reverse
from django.utils import timezone

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import QuerySet
from django.views.generic import CreateView, DetailView, ListView, TemplateView

from accounts.models import CustomUser, SignerUser

from .forms import PdfValidateForm
from .models import PdfDocumentValidator


class ValidateSignatureView(LoginRequiredMixin, CreateView):
    """View to validate the signature of the PDF."""

    form_class = PdfValidateForm
    template_name = "signature_validator/home.html"

    def get_success_url(self):
        """Get the success URL."""
        return self.object.get_absolute_url()

    def get_form_kwargs(self):
        """Get the form kwargs set request."""
        kwargs = super(ValidateSignatureView, self).get_form_kwargs()
        kwargs["request"] = self.request
        return kwargs


class PDFResultView(LoginRequiredMixin, DetailView):
    """View to show the result of the PDF validation."""

    model = PdfDocumentValidator
    template_name = "signature_validator/pdf_result.html"

    def get_context_data(self, **kwargs):
        """Get the context data to template."""
        context = super().get_context_data(**kwargs)
        context["pdf_restult"] = self.get_object()
        return context


class PDFResultReportView(DetailView):
    """View to show the result of the PDF validation."""

    model = PdfDocumentValidator
    template_name = "signature_validator/pdf_validation_report_with_styles.html"

    def get_context_data(self, **kwargs):
        """Get the context data to template."""
        context = super().get_context_data(**kwargs)
        context["pdf_restult"] = self.get_object()
        return context


class ValidatedPDFListView(LoginRequiredMixin, ListView):
    """View to show the list of validated PDFs."""

    model = PdfDocumentValidator
    template_name = "signature_validator/pdf_list.html"
    context_object_name = "pdf_list"
    paginate_by = 10

    def get_queryset(self):
        """Get the queryset for the view filtered by logged in user."""
        return PdfDocumentValidator.objects.filter(user=self.request.user).order_by(
            "-created"
        )


class ReportView(TemplateView):
    """View to show the report of the validated PDFs."""

    template_name = "signature_validator/report.html"

    def get_context_data(self, **kwargs):
        """Get the context data for the view."""
        context = super().get_context_data(**kwargs)
        validated_pdf: QuerySet[PdfDocumentValidator] = (
            PdfDocumentValidator.objects.all()
        )
        context["pdf_docs_tested"] = validated_pdf.count()
        context["verified_pdf"] = validated_pdf.filter(
            all_signers_verified=True
        ).count()
        context["pdf_not_verified"] = validated_pdf.filter(
            all_signers_verified=False
        ).count()
        context["users_count"] = CustomUser.objects.all().count()
        context["signers_count"] = SignerUser.objects.all().count()
        context["today_date"] = timezone.now().date()
        signed_documents_data = []
        days = []

        for i in range(0, 5):
            current_day = timezone.now() - timedelta(days=i)
            start_of_day = current_day.replace(
                hour=0, minute=0, second=0, microsecond=0
            )
            end_of_day = current_day.replace(
                hour=23, minute=59, second=59, microsecond=999999
            )
            signed_documents_count = PdfDocumentValidator.objects.filter(
                is_signed=True, created__range=(start_of_day, end_of_day)
            ).count()
            signed_documents_data.append(signed_documents_count)
            days.append(str(current_day.date()))
        context["signed_documents_labels"] = days
        context["signed_documents_data"] = signed_documents_data

        users_data = []
        users_label = []
        for i in range(0, 6):
            current_day = timezone.now() - timedelta(days=i)
            start_of_day = current_day.replace(
                hour=0, minute=0, second=0, microsecond=0
            )
            end_of_day = current_day.replace(
                hour=23, minute=59, second=59, microsecond=999999
            )
            users_joined_count = CustomUser.objects.filter(
                is_active=True, date_joined__range=(start_of_day, end_of_day)
            ).count()
            users_data.append(users_joined_count)
            users_label.append(str(current_day.date()))
        context["signed_documents_labels"] = days
        context["signed_documents_data"] = signed_documents_data
        context["users_data"] = users_data
        context["users_label"] = users_label
        return context


@login_required
def generate_pdf_report(request, *args, **kwargs):
    """Generate the PDF report of the validated PDFs."""
    pdf = pdfkit.from_url(
        request.build_absolute_uri(
            reverse(
                "signature-validator-view:pdf-result-report",
                kwargs={"pk": kwargs.get("pk")},
            )
        ),
        False,
    )
    response = HttpResponse(pdf, content_type="application/pdf")
    response["Content-Disposition"] = 'attachment; filename="report.pdf"'
    return response

signature_validator/templates/signature_validator/home.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Validate PDF{% endblock %}

{% block content %}
    <div class="container">
        <div class="row mt-5">
            <div class="col-lg-6 col-md-4 col-sm-12">

            <h2 class="card-title text-center mb-4">PDF Validation</h2>
                <img src="{% static 'img/pdf-home.png' %}" class="center-image" height="270px" alt="">
                <p class="card-text">PDF validation is the process of ensuring that a PDF
                    document complies with
                    certain standards or criteria, such as format specifications or digital
                    signatures. It is
                    important because:</p>
                <ul class="card-text">
                    <li>It helps ensure the integrity and authenticity of the document,
                        making it reliable
                        for legal and official purposes.
                    </li>
                    <li>It prevents tampering or unauthorized modifications to the document,
                        preserving its
                        original content.
                    </li>
                    <li>It enhances document security by verifying digital signatures and
                        encryption, if
                        applicable.
                    </li>
                    <li>It ensures compatibility with different software and devices, as
                        compliant PDFs are
                        more likely to render correctly across platforms.
                    </li>
                </ul>
            </div>

            <div class="col-lg-6 col-md-4 col-sm-12 mt-3">
                <div class="card">
                    <div class="card-body">
                        <h2 class="text-danger text-center mb-5">Upload the PDF to Validate</h2>
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form | crispy }}

                            <div class="text-right mt-5">
                                <button class="btn btn-outline-danger border-radius-one" type="submit">Validate
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

signature_validator/templates/signature_validator/pdf_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}My Validated PDF list{% endblock %}

{% block content %}
    <div class="container">
        {% if pdf_list %}
            <div class="col-12">
                <div class="text-center">
                    <img src="{% static 'img/pdf-home.png' %}" height="250px"
                         class=" d-inline center-image"
                         alt="">
                    <h2 class="d-inline text-danger">Validated PDF list</h2>
                </div>
            </div>
        {% endif %}
        <div class="row mt-5">


            <div class="col-12 mt-5">
                <table class="table table-bordered">
                    {% if pdf_list %}
                        <thead>
                    <tr class="font-weight-bold text-center">
                        <th scope="col">ID</th>
                        <th scope="col">Verified</th>
                        <th scope="col">Hashes Valid</th>
                        <th scope="col">Signatures Valid</th>
                        <th scope="col">Check</th>
                        <th scope="col">Download</th>
                    </tr>
                    </thead>
                    {% endif %}
                    <tbody>
                    {% for pdf in pdf_list %}
                        <tr class="text-center">
                            <th scope="row"> {{ pdf.pk }}</th>
                            <td >
                                {% if pdf.all_signers_verified %}
                                    <i class="fas fa-check-circle green-circle"></i>
                                {% else %}
                                    <i class="fas fa-times-circle red-circle"></i>
                                {% endif %}
                            </td>

                            <td>
                                {% if pdf.is_hashes_valid %}
                                    <i class="fas fa-check-circle green-circle"></i>
                                {% else %}
                                    <i class="fas fa-times-circle red-circle"></i>
                                {% endif %}
                            </td>
                            <td>
                                {% if pdf.is_signatures_valid %}
                                    <i class="fas fa-check-circle green-circle"></i>
                                {% else %}
                                    <i class="fas fa-times-circle red-circle"></i>
                                {% endif %}
                            </td>
                            <td><a href="{% url 'signature-validator-view:pdf-result' pdf.pk %}"
                                   class="btn btn-outline-success border-radius-one">Details</a>
                            </td>
                            <td><a href="{{ pdf.pdf_file.url }}"
                                   target="_blank"
                                   class="btn btn-outline-danger border-radius-one">Download PDF</a>
                            </td>
                        </tr>
                    {% empty %}
                        <div class="col-12">
                            <div class="text-center">
                                <img src="{% static 'img/pdf-home.png' %}" height="250px"
                                     class=" d-inline center-image"
                                     alt="">
                                <h2 class="d-inline text-danger">You don't have any validated PDF documents.</h2>
                            </div>
                        </div>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="mt-5">
            {% include 'base/paginator.html' %}
        </div>
    </div>

{% endblock %}

signature_validator/templates/signature_validator/pdf_result.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Verified Outcomes{% endblock %}

{% block content %}
    <div class="container">
        <div class="row mt-5">
            <div class="col-lg-9 col-sm-12">
                {% include 'signature_validator/pdf_validation_report.html' %}
                <div class="text-right mt-5 mb-5">
                    <a href="{% url 'signature-validator-view:pdf-result-download' pdf_restult.pk %}"
                       class="btn btn-outline-success border-radius-one">Download Validation Report</a>
                </div>
            </div>
            <div class="col-lg-3 col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <h3 class="text-danger mb-5 text-center">Actions</h3>
                        <img class="center-image" src="{% static 'img/pdf-download-2617.svg' %}"
                             height="100px" alt="download pdf">
                        <div class="text-center mt-3">
                            <a href="{{ pdf_restult.pdf_file.url }}"

                           target="_blank"
                               class="btn btn-outline-danger border-radius-one">Download PDF</a>
                        </div>

                        <img class="center-image mt-5" src="{% static 'img/pdf-validation.png' %}"
                             height="100px" alt="download pdf">
                        <div class="text-center mt-3">
                            <a href="{% url 'signature-validator-view:validate-signature' %}"
                               class="btn btn-outline-success border-radius-one">Validate another
                                PDF</a>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

signature_validator/templates/signature_validator/pdf_validation_report.html
{% load static %}

{% if pdf_restult %}
    <div class="card">
        <div class="card-body">
            <h2 class="text-info mb-5 text-center underline-text">PDF Validation Report. </h2>
            <div class="row">

                <div class="col-7">
                    <div class="w-full text-base text-gray-800 leading-7">
                        The PDF is
                        {% if pdf_restult.all_signers_verified %}
                            <span class="text-success "> verified <i
                                    class="fas fa-check-circle green-circle"></i> </span>
                        {% else %}
                            <span class="text-danger"> is not verified.
                                            <i class="fas fa-times-circle red-circle"></i>
                                            </span>
                        {% endif %}
                    </div>
                    <div class="w-full text-base text-gray-800 leading-7">

                        All signatures are
                        {% if pdf_restult.is_signatures_valid %}
                            <span class="text-success"> Valid.
                                                <i class="fas fa-check-circle green-circle"></i> </span>
                        {% else %}
                            <span class="text-danger"> Not Signed.
                                                <i class="fas fa-times-circle red-circle"></i>
                                            </span>
                        {% endif %}
                    </div>

                    <div class="w-full text-base text-gray-800 leading-7">
                        Hashes are
                        {% if pdf_restult.is_hashes_valid %}
                            <span class="text-success"> Valid. <i
                                    class="fas fa-check-circle green-circle"></i></span>
                        {% else %}
                            <span class="text-danger"> not valid, The document has been modified.
                                                <i class="fas fa-times-circle red-circle"></i>
                                            </span>
                        {% endif %}
                    </div>
                    <div class="w-full text-base text-gray-800 leading-7">
                        The PDF is
                        {% if pdf_restult.is_signed %}
                            <span class="text-success ">digitally signed. <i
                                    class="fas fa-check-circle green-circle"></i> </span>
                        {% else %}
                            <span class="text-danger">digitally not signed.
                                            <i class="fas fa-times-circle red-circle"></i>
                                            </span>
                        {% endif %}
                    </div>
                    <p class="w-full text-base text-gray-800 leading-7">
                        This PDF has signed by {{ pdf_restult.distinct_people_signed }} people, and
                        there are
                        {{ pdf_restult.signaturevalidator_set.count }} signatures.</p>
                    <div class="mb-5 mt-5">
                        {% if pdf_restult.updated %}
                            Date of Validation:
                            <span class="text-secondary"> {{ pdf_restult.updated }}</span>
                        {% endif %}
                    </div>
                </div>
                <div class="col-5">
                    <img src="{% static 'img/fill_and_sign.svg' %}" height="200px"
                         class="center-image" alt="Signature">
                </div>
            </div>

            <div class="row">
                <div class="col-11">
                    {% for signaturevalidator in pdfdocumentvalidator.signaturevalidator_set.all %}
                        <h4 class="text-info text-center mt-5">{{ signaturevalidator.signature_name }}</h4>
                        <table class="table table-bordered mb-3">

                            <tbody>
                            <tr>
                                <td><span class="font-weight-bold">Hash</span>
                                </td>
                                <td colspan="3">
                                    {% if signaturevalidator.hash_valid %}
                                        <i class="fas fa-check-circle green-circle"></i>

                                        <span class="text-success"> Valid.
                                                                    </span>
                                    {% else %}
                                        <i class="fas fa-times-circle red-circle"></i>

                                        <span class="text-danger"> Invalid.
                                                                </span>
                                        <p>This document has been modified.</p>
                                    {% endif %}
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <span class="font-weight-bold">Signature Valid:</span>
                                </td>
                                <td colspan="3">
                                    {% if signaturevalidator.signature_valid %}
                                        <i class="fas fa-check-circle green-circle"></i>

                                        <span class="text-success"> valid.
                                                                        </span>
                                    {% else %}
                                        <i class="fas fa-times-circle red-circle"></i>

                                        <span class="text-danger"> invalid.
                                                                    </span>
                                    {% endif %}
                                </td>
                            </tr>
                            <tr>
                                <td><span class="font-weight-bold">Verified Signer:</span>
                                </td>
                                <td colspan="3">
                                    {% if signaturevalidator.verified_signer %}
                                        <i class="fas fa-check-circle green-circle"></i>

                                        <span class="text-success"> Signer is verified in the system
                                                                </span>
                                    {% else %}
                                        <i class="fas fa-times-circle red-circle"></i>

                                        <span class="text-danger"> Signer is not verified in the system
                                                                </span>
                                    {% endif %}
                                </td>
                            </tr>
                            {% if signaturevalidator.message %}
                                <tr>
                                    <td><span
                                            class="font-weight-bold">Message:</span>
                                    </td>
                                    <td colspan="3"><span
                                            class="text-secondary">{{ signaturevalidator.message }}</span>
                                    </td>
                                </tr>
                            {% endif %}
                            <tr>
                                <td><span class="font-weight-bold">Signed by:</span></td>
                                <td colspan="3">
                                    {% if signaturevalidator.signer_user %}
                                        <a href="{% url 'accounts:detail' signaturevalidator.signer_user.pk %}">
                                            {{ signaturevalidator.signed_by }}
                                        </a>
                                    {% else %}
                                        {{ signaturevalidator.signed_by }}
                                    {% endif %}
                                </td>
                            </tr>

                            <tr>
                                <td><span class="font-weight-bold">Signer's Email:</span></td>
                                <td colspan="3"> {{ signaturevalidator.email_of_signer }}</td>
                            </tr>
                            <tr>
                                <td><span class="font-weight-bold">Signature placed at:</span></td>
                                <td colspan="3">{{ signaturevalidator.signing_time }}</td>
                            </tr>
                            </tbody>
                        </table>

                    {% endfor %}
                </div>
            </div>

        </div>

    </div>
{% endif %}

signature_validator/templates/signature_validator/pdf_validation_report_with_styles.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- responsive tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Some author">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">
    <!-- SEO Meta Tags-->
     <link rel="home" href="https://{{ request.META.HTTP_HOST }}.com/" />
    <title>
        Validator
        {% block head_title %}

        {% endblock %}
    </title>
    <meta name="description" content="{% block meta_description %}{% endblock %}">
    <link href="https://{{ request.META.HTTP_HOST }}.com{{request.path}}" rel="canonical">
    <meta name="keywords" content="{% block keywords %} {% endblock %}">

    <!-- additional CSS tags -->
    {% block extrastyle %}{% endblock extrastyle %}

    <!-- addition JS or SEO tags -->
    {% block extra_head_top %}{% endblock extra_head_top %}

    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="theme-color" content="#ffffff">

     <!-- common CSS files -->
    {% include 'base/css.html' %}

</head>
<body>
    {% include 'signature_validator/pdf_validation_report.html' %}

    <!-- common JS files -->
    {% include 'base/js.html' %}


</body>
</html>